#ifndef BITCOINSILVER_CHAINPARAMSSEEDS_H
#define BITCOINSILVER_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the bitcoinsilver network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a BIP155 serialized (networkID, addr, port) tuple.
 */
static const uint8_t chainparams_seed_main[] = {
    0x01,0x04,0xd5,0xa5,0x53,0x5e,0x29,0x46
    0x01,0x04,0x4e,0x8a,0x2d,0x13,0x29,0x46,
    0x01,0x04,0x6d,0xcd,0xb5,0xab,0x29,0x46,
};

static const uint8_t chainparams_seed_test[] = {
};
#endif // BITCOINSILVER_CHAINPARAMSSEEDS_H
