#ifndef BITCOIN_SILVER_CHAINPARAMSSEEDS_H
#define BITCOIN_SILVER_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the bitcoin_silver network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a BIP155 serialized (networkID, addr, port) tuple.
 */
static const uint8_t chainparams_seed_main[] = {
    0x01, 0x04, 0x6D, 0xCD, 0xB5, 0xAB, 0x00, 0x00,
    // Weitere Seed-Nodes hier hinzufügen, falls erforderlich
};

static const uint8_t chainparams_seed_test[] = {
    
};
#endif // BITCOIN_SILVER_CHAINPARAMSSEEDS_H
